const pathlib=require('path');
const htmlWebpackPlugin=require('html-webpack-plugin');

module.exports={
    entry:pathlib.resolve('./src/js/index.js'),
    output:{
        filename:'js/bundle.js',
        path:pathlib.resolve('build/')
    },
    module:{
        rules:[
            //处理less资源
            {
                test:/\.less$/,
                use:[
                    'style-loader',
                    'css-loader',
                    'less-loader'
                ]
            },
            //处理css资源
            {
                test:/\.css$/,
                use:[
                    'style-loader',
                    'css-loader'
                ]
            },
            //处理css中的图片资源
            {
                test:/\.(jpg|png|jpeg|gif)$/,
                loader:'url-loader',
                options:{
                    limit:8*1024,
                    name:'[hash:10].[ext]',
                    esModule:false,
                    outputPath:'imgs'
                }
            },
            //处理html文件中的图片资源
            {
                test:/\.html$/, 
                loader:'html-loader',
                options:{
                     esModule:false
                }
            },
            //处理其他资源
            {
                exclude:/\.(html|js|css|less|png|jpeg|jpg|gif)$/,
                loader:'file-loader',
                options:{
                    name:'[hash:10].[ext]',
                    outputPath:'media'
                }
            }
        ]
    },
    plugins:[
        //处理html文件，设置模板
        new htmlWebpackPlugin({
            template:'./src/index.html'
        })
    ],
    //设置开发服务器
    devServer:{
        contentBase:pathlib.resolve('build/'),
        compress:true,
        port:3000
    },
    mode:'development'
       
}